# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Ticket types

class TicketOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Ticket create method"""
    id: _int
    createdAt: datetime.datetime


class TicketCreateInput(TicketOptionalCreateInput):
    """Required arguments to the Ticket create method"""
    titulo: _str
    estado: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class TicketOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Ticket create method, without relations"""
    id: _int
    createdAt: datetime.datetime


class TicketCreateWithoutRelationsInput(TicketOptionalCreateWithoutRelationsInput):
    """Required arguments to the Ticket create method, without relations"""
    titulo: _str
    estado: _str

class TicketConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'TicketCreateWithoutRelationsInput'
    where: 'TicketWhereUniqueInput'

class TicketCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'TicketCreateWithoutRelationsInput'
    connect: 'TicketWhereUniqueInput'
    connect_or_create: 'TicketConnectOrCreateWithoutRelationsInput'


class TicketCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['TicketCreateWithoutRelationsInput', List['TicketCreateWithoutRelationsInput']]
    connect: Union['TicketWhereUniqueInput', List['TicketWhereUniqueInput']]
    connect_or_create: Union['TicketConnectOrCreateWithoutRelationsInput', List['TicketConnectOrCreateWithoutRelationsInput']]

_TicketWhereUnique_id_Input = TypedDict(
    '_TicketWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

TicketWhereUniqueInput = _TicketWhereUnique_id_Input


class TicketUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    titulo: _str
    estado: _str
    createdAt: datetime.datetime


class TicketUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    titulo: _str
    estado: _str
    createdAt: datetime.datetime


class TicketUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['TicketCreateWithoutRelationsInput']
    connect: List['TicketWhereUniqueInput']
    connect_or_create: List['TicketConnectOrCreateWithoutRelationsInput']
    set: List['TicketWhereUniqueInput']
    disconnect: List['TicketWhereUniqueInput']
    delete: List['TicketWhereUniqueInput']

    # TODO
    # update: List['TicketUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['TicketUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['TicketScalarWhereInput']
    # upsert: List['TicketUpserteWithWhereUniqueWithoutRelationsInput']


class TicketUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'TicketCreateWithoutRelationsInput'
    connect: 'TicketWhereUniqueInput'
    connect_or_create: 'TicketConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'TicketUpdateInput'
    # upsert: 'TicketUpsertWithoutRelationsInput'


class TicketUpsertInput(TypedDict):
    create: 'TicketCreateInput'
    update: 'TicketUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Ticket_id_OrderByInput = TypedDict(
    '_Ticket_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Ticket_titulo_OrderByInput = TypedDict(
    '_Ticket_titulo_OrderByInput',
    {
        'titulo': 'SortOrder',
    },
    total=True
)

_Ticket_estado_OrderByInput = TypedDict(
    '_Ticket_estado_OrderByInput',
    {
        'estado': 'SortOrder',
    },
    total=True
)

_Ticket_createdAt_OrderByInput = TypedDict(
    '_Ticket_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_Ticket_RelevanceInner = TypedDict(
    '_Ticket_RelevanceInner',
    {
        'fields': 'List[TicketScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Ticket_RelevanceOrderByInput = TypedDict(
    '_Ticket_RelevanceOrderByInput',
    {
        '_relevance': '_Ticket_RelevanceInner',
    },
    total=True
)

TicketOrderByInput = Union[
    '_Ticket_id_OrderByInput',
    '_Ticket_titulo_OrderByInput',
    '_Ticket_estado_OrderByInput',
    '_Ticket_createdAt_OrderByInput',
    '_Ticket_RelevanceOrderByInput',
]



# recursive Ticket types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

TicketRelationFilter = TypedDict(
    'TicketRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class TicketListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class TicketInclude(TypedDict, total=False):
    """Ticket relational arguments"""


    

class TicketIncludeFromTicket(TypedDict, total=False):
    """Relational arguments for Ticket"""


class TicketIncludeFromTicketRecursive1(TypedDict, total=False):
    """Relational arguments for Ticket"""


class TicketIncludeFromTicketRecursive2(TypedDict, total=False):
    """Relational arguments for Ticket"""


class TicketIncludeFromTicketRecursive3(TypedDict, total=False):
    """Relational arguments for Ticket"""


class TicketIncludeFromTicketRecursive4(TypedDict, total=False):
    """Relational arguments for Ticket"""

    

class TicketArgsFromTicket(TypedDict, total=False):
    """Arguments for Ticket"""
    include: 'TicketIncludeFromTicketRecursive1'


class TicketArgsFromTicketRecursive1(TypedDict, total=False):
    """Arguments for Ticket"""
    include: 'TicketIncludeFromTicketRecursive2'


class TicketArgsFromTicketRecursive2(TypedDict, total=False):
    """Arguments for Ticket"""
    include: 'TicketIncludeFromTicketRecursive3'


class TicketArgsFromTicketRecursive3(TypedDict, total=False):
    """Arguments for Ticket"""
    include: 'TicketIncludeFromTicketRecursive4'


class TicketArgsFromTicketRecursive4(TypedDict, total=False):
    """Arguments for Ticket"""
    
    

class FindManyTicketArgsFromTicket(TypedDict, total=False):
    """Arguments for Ticket"""
    take: int
    skip: int
    order_by: Union['TicketOrderByInput', List['TicketOrderByInput']]
    where: 'TicketWhereInput'
    cursor: 'TicketWhereUniqueInput'
    distinct: List['TicketScalarFieldKeys']
    include: 'TicketIncludeFromTicketRecursive1'


class FindManyTicketArgsFromTicketRecursive1(TypedDict, total=False):
    """Arguments for Ticket"""
    take: int
    skip: int
    order_by: Union['TicketOrderByInput', List['TicketOrderByInput']]
    where: 'TicketWhereInput'
    cursor: 'TicketWhereUniqueInput'
    distinct: List['TicketScalarFieldKeys']
    include: 'TicketIncludeFromTicketRecursive2'


class FindManyTicketArgsFromTicketRecursive2(TypedDict, total=False):
    """Arguments for Ticket"""
    take: int
    skip: int
    order_by: Union['TicketOrderByInput', List['TicketOrderByInput']]
    where: 'TicketWhereInput'
    cursor: 'TicketWhereUniqueInput'
    distinct: List['TicketScalarFieldKeys']
    include: 'TicketIncludeFromTicketRecursive3'


class FindManyTicketArgsFromTicketRecursive3(TypedDict, total=False):
    """Arguments for Ticket"""
    take: int
    skip: int
    order_by: Union['TicketOrderByInput', List['TicketOrderByInput']]
    where: 'TicketWhereInput'
    cursor: 'TicketWhereUniqueInput'
    distinct: List['TicketScalarFieldKeys']
    include: 'TicketIncludeFromTicketRecursive4'


class FindManyTicketArgsFromTicketRecursive4(TypedDict, total=False):
    """Arguments for Ticket"""
    take: int
    skip: int
    order_by: Union['TicketOrderByInput', List['TicketOrderByInput']]
    where: 'TicketWhereInput'
    cursor: 'TicketWhereUniqueInput'
    distinct: List['TicketScalarFieldKeys']
    


FindManyTicketArgs = FindManyTicketArgsFromTicket
FindFirstTicketArgs = FindManyTicketArgsFromTicket


    

class TicketWhereInput(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    titulo: Union[_str, 'types.StringFilter']
    estado: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['TicketWhereInputRecursive1', List['TicketWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['TicketWhereInputRecursive1']
    OR: List['TicketWhereInputRecursive1']
    NOT: List['TicketWhereInputRecursive1']


class TicketWhereInputRecursive1(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    titulo: Union[_str, 'types.StringFilter']
    estado: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['TicketWhereInputRecursive2', List['TicketWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['TicketWhereInputRecursive2']
    OR: List['TicketWhereInputRecursive2']
    NOT: List['TicketWhereInputRecursive2']


class TicketWhereInputRecursive2(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    titulo: Union[_str, 'types.StringFilter']
    estado: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['TicketWhereInputRecursive3', List['TicketWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['TicketWhereInputRecursive3']
    OR: List['TicketWhereInputRecursive3']
    NOT: List['TicketWhereInputRecursive3']


class TicketWhereInputRecursive3(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    titulo: Union[_str, 'types.StringFilter']
    estado: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['TicketWhereInputRecursive4', List['TicketWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['TicketWhereInputRecursive4']
    OR: List['TicketWhereInputRecursive4']
    NOT: List['TicketWhereInputRecursive4']


class TicketWhereInputRecursive4(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    titulo: Union[_str, 'types.StringFilter']
    estado: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate Ticket types


    

class TicketScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    titulo: Union[_str, 'types.StringWithAggregatesFilter']
    estado: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['TicketScalarWhereWithAggregatesInputRecursive1']
    OR: List['TicketScalarWhereWithAggregatesInputRecursive1']
    NOT: List['TicketScalarWhereWithAggregatesInputRecursive1']


class TicketScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    titulo: Union[_str, 'types.StringWithAggregatesFilter']
    estado: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['TicketScalarWhereWithAggregatesInputRecursive2']
    OR: List['TicketScalarWhereWithAggregatesInputRecursive2']
    NOT: List['TicketScalarWhereWithAggregatesInputRecursive2']


class TicketScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    titulo: Union[_str, 'types.StringWithAggregatesFilter']
    estado: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['TicketScalarWhereWithAggregatesInputRecursive3']
    OR: List['TicketScalarWhereWithAggregatesInputRecursive3']
    NOT: List['TicketScalarWhereWithAggregatesInputRecursive3']


class TicketScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    titulo: Union[_str, 'types.StringWithAggregatesFilter']
    estado: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['TicketScalarWhereWithAggregatesInputRecursive4']
    OR: List['TicketScalarWhereWithAggregatesInputRecursive4']
    NOT: List['TicketScalarWhereWithAggregatesInputRecursive4']


class TicketScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Ticket arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    titulo: Union[_str, 'types.StringWithAggregatesFilter']
    estado: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class TicketGroupByOutput(TypedDict, total=False):
    id: _int
    titulo: _str
    estado: _str
    createdAt: datetime.datetime
    _sum: 'TicketSumAggregateOutput'
    _avg: 'TicketAvgAggregateOutput'
    _min: 'TicketMinAggregateOutput'
    _max: 'TicketMaxAggregateOutput'
    _count: 'TicketCountAggregateOutput'


class TicketAvgAggregateOutput(TypedDict, total=False):
    """Ticket output for aggregating averages"""
    id: float


class TicketSumAggregateOutput(TypedDict, total=False):
    """Ticket output for aggregating sums"""
    id: _int


class TicketScalarAggregateOutput(TypedDict, total=False):
    """Ticket output including scalar fields"""
    id: _int
    titulo: _str
    estado: _str
    createdAt: datetime.datetime


TicketMinAggregateOutput = TicketScalarAggregateOutput
TicketMaxAggregateOutput = TicketScalarAggregateOutput


class TicketMaxAggregateInput(TypedDict, total=False):
    """Ticket input for aggregating by max"""
    id: bool
    titulo: bool
    estado: bool
    createdAt: bool


class TicketMinAggregateInput(TypedDict, total=False):
    """Ticket input for aggregating by min"""
    id: bool
    titulo: bool
    estado: bool
    createdAt: bool


class TicketNumberAggregateInput(TypedDict, total=False):
    """Ticket input for aggregating numbers"""
    id: bool


TicketAvgAggregateInput = TicketNumberAggregateInput
TicketSumAggregateInput = TicketNumberAggregateInput


TicketCountAggregateInput = TypedDict(
    'TicketCountAggregateInput',
    {
        'id': bool,
        'titulo': bool,
        'estado': bool,
        'createdAt': bool,
        '_all': bool,
    },
    total=False,
)

TicketCountAggregateOutput = TypedDict(
    'TicketCountAggregateOutput',
    {
        'id': int,
        'titulo': int,
        'estado': int,
        'createdAt': int,
        '_all': int,
    },
    total=False,
)


TicketKeys = Literal[
    'id',
    'titulo',
    'estado',
    'createdAt',
]
TicketScalarFieldKeys = Literal[
    'id',
    'titulo',
    'estado',
    'createdAt',
]
TicketScalarFieldKeysT = TypeVar('TicketScalarFieldKeysT', bound=TicketScalarFieldKeys)

TicketRelationalFieldKeys = _NoneType



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields